--SUBQUERY AND JOIN

--QUESTION 1
select * from branch1 join staff1 on branch1.branchno=staff1.branchno where street='8 Jefferson Way';
--QUESTION 2
SELECT * FROM STAFF1 WHERE BRANCHNO=ANY(SELECT BRANCHNO FROM BRANCH1 WHERE STATE='WA');
--QUESTION 3
SELECT * FROM STAFF1 WHERE SALARY>(SELECT AVG(SALARY) FROM STAFF1);
--QUESTION 4
SELECT V.CATALOGNO,V.TITLE,D.DIRECTORNAME 
FROM VIDEO1 V JOIN DIRECTOR1 D ON V.DIRECTORNO=D.DIRECTORNO;
--QUESTION 5
SELECT V.CATALOGNO,V.TITLE,D.DIRECTORNAME,A.ACTORNAME,R.CHARACTER 
	FROM VIDEO1 V,DIRECTOR1 D,ACTOR1 A,ROLE1 R
	WHERE V.CATALOGNO=R.CATALOGNO AND R.ACTORNO=A.ACTORNO AND V.DIRECTORNO=D.DIRECTORNO 
	ORDER BY TITLE;
--QUESTION 6
SELECT ACTORNAME 
	FROM ACTOR1 
	JOIN (SELECT ACTORNO 
			AS A FROM ROLE1 
			GROUP BY ACTORNO 
			HAVING COUNT(ACTORNO) > 2) 
	ON A=ACTORNO;
--QUESTION 7
SELECT V2.BRANCHNO,V1.CATALOGNO,V1.TITLE FROM VIDEO1 V1 JOIN VIDEOFORRENT1 V2 ON V1.CATALOGNO=V2.CATALOGNO;
--QUESTION 8
SELECT * FROM BRANCH1 B JOIN STAFF1 S ON B.BRANCHNO=S.BRANCHNO JOIN REGISTRATION1 R ON R.STAFFNO=S.STAFFNO WHERE DATEJOINED> '31-MAY-00';


