--SWB AND JOIN SQL

--QUESTION 1
select * from branch3 join staff3 on branch3.branchno=staff3.branchno where street='8 Jefferson Way';
--QUESTION 2
SELECT * FROM STAFF3 WHERE BRANCHNO=ANY(SELECT BRANCHNO FROM BRANCH3 WHERE STATE='WA');
--QUESTION 3
SELECT * FROM STAFF3 WHERE SALARY>(SELECT AVG(SALARY) FROM STAFF3);
--QUESTION 4
SELECT V.CATALOGNO,V.TITLE,D.DIRECTORNAME 
FROM VIDEO3 V JOIN DIRECTOR3 D ON V.DIRECTORNO=D.DIRECTORNO;
--QUESTION 5
SELECT V.CATALOGNO,V.TITLE,D.DIRECTORNAME,A.ACTORNAME,R.CHARACTER 
FROM VIDEO3 V,DIRECTOR3 D,ACTOR3 A,ROLE3 R
WHERE V.CATALOGNO=R.CATALOGNO AND R.ACTORNO=A.ACTORNO AND V.DIRECTORNO=D.DIRECTORNO 
ORDER BY TITLE;
--QUESTION 6
SELECT ACTORNAME FROM ACTOR3 JOIN (SELECT ACTORNO AS A FROM ROLE3 GROUP BY ACTORNO HAVING COUNT(ACTORNO) > 2) ON A=ACTORNO;
--QUESTION 7
SELECT V2.BRANCHNO,V3.CATALOGNO,V3.TITLE FROM VIDEO3 V3 JOIN VIDEOFORRENT3 V2 ON V3.CATALOGNO=V2.CATALOGNO;
--QUESTION 8
SELECT * FROM BRANCH3 B JOIN STAFF3 S ON B.BRANCHNO=S.BRANCHNO JOIN REGISTRATION3 R ON R.STAFFNO=S.STAFFNO WHERE DATEJOINED> '31-MAY-00';
