-- Question 1
 create table DEPARTMENT(DEP_ID NUMBER, DEPT_NAME VARCHAR2(10), MANAGER_ID NUMBER);
 CREATE SEQUENCE DEPT_ID_SEQ MINVALUE 200 MAXVALUE 1000 START WITH 200 INCREMENT BY 10 CACHE 20;
 INSERT INTO DEPARTMENT VALUES (DEPT_ID_SEQ.NEXTVAL, 'CS', '123');
 INSERT INTO DEPARTMENT VALUES (DEPT_ID_SEQ.NEXTVAL, 'CS', '124');
 --Question 2
 drop sequence DEPT_ID_SEQ;